- name: Install NGINX
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: Start and enable NGINX
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

- name: run app pre-requsites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

  - name: Copy backend configuration
    ansible.builtin.template:
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify:
    - restart nginx